# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/docs/pubcrawler',
                'doc_host': 'https://docs.autonomy.work',
                'git_url': 'https://github.com/Autonomy-Data-Unit/pubcrawler',
                'lib_path': 'pubcrawler'},
  'syms': { 'pubcrawler.cli.core': {'pubcrawler.cli.core.main': ('cli/cli_01_core.html#main', 'pubcrawler/cli/core.py')},
            'pubcrawler.cli.foo': {'pubcrawler.cli.foo.main': ('cli/cli_02_foo.html#main', 'pubcrawler/cli/foo.py')},
            'pubcrawler.const': {},
            'pubcrawler.core.01_clear_dir': { 'pubcrawler.core.01_clear_dir.delete_all_files_from_dir': ( 'core/clean.html#delete_all_files_from_dir',
                                                                                                          'pubcrawler/core/01_clear_dir.py')},
            'pubcrawler.core.01_first_steps': {},
            'pubcrawler.tools.foo': {'pubcrawler.tools.foo.foo': ('tools/foo.html#foo', 'pubcrawler/tools/foo.py')},
            'pubcrawler.utils.general': { 'pubcrawler.utils.general.hello_world': ( 'utils/utils_01_general.html#hello_world',
                                                                                    'pubcrawler/utils/general.py')}}}
