# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utils/utils_01_general.ipynb.

# %% auto 0
__all__ = ['hello_world']

# %% ../../nbs/utils/utils_01_general.ipynb 5
import adu_template_main as proj
from .. import const, log, utils, tools
import adu_proj.utils as adutils

# %% ../../nbs/utils/utils_01_general.ipynb 7
def hello_world():
    print('Hello world!')
