# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/docs/adu-template-main',
                'doc_host': 'https://docs.autonomy.work',
                'git_url': 'https://github.com/Autonomy-Data-Unit/adu-template-main',
                'lib_path': 'adu_template_main'},
  'syms': { 'adu_template_main.cli.core': { 'adu_template_main.cli.core.main': ( 'cli/cli_01_core.html#main',
                                                                                 'adu_template_main/cli/core.py')},
            'adu_template_main.cli.foo': {'adu_template_main.cli.foo.main': ('cli/cli_02_foo.html#main', 'adu_template_main/cli/foo.py')},
            'adu_template_main.const': {},
            'adu_template_main.core.01_first_steps': {},
            'adu_template_main.tools.foo': {'adu_template_main.tools.foo.foo': ('tools/foo.html#foo', 'adu_template_main/tools/foo.py')},
            'adu_template_main.utils.general': { 'adu_template_main.utils.general.hello_world': ( 'utils/utils_01_general.html#hello_world',
                                                                                                  'adu_template_main/utils/general.py')}}}
