# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/tools/01_foo.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../../nbs/tools/01_foo.ipynb 5
import pubcrawler as proj
from .. import const, log, utils, tools
# import adu_proj.utils as adutils

# %% ../../nbs/tools/01_foo.ipynb 7
def foo(a, b):
    return float(a) + float(b)
