# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/01_first_steps.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/core/01_first_steps.ipynb 5
import pubcrawler as proj
from .. import const, log, utils, tools
import adu_proj.utils as adutils

# %% ../../nbs/core/01_first_steps.ipynb 8
log.info('Doing some stuff')
