# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/04_metadata.ipynb.

# %% auto 0
__all__ = ['API_KEY', 'client', 'extract_text_from_first_n_pages']

# %% ../../nbs/core/04_metadata.ipynb 4
import pubcrawler as proj
from .. import const, log, utils, tools
import adu_proj.utils as adutils

# %% ../../nbs/core/04_metadata.ipynb 6
load_dotenv()
API_KEY = os.getenv("OPENAI_API_KEY")
client = OpenAI(
    # This is the default and can be omitted
    api_key=API_KEY,
)

# %% ../../nbs/core/04_metadata.ipynb 8
with open(f'{const.pre_output_path}/data_files.json', 'r') as f:
    file_links = json.load(f)

# %% ../../nbs/core/04_metadata.ipynb 9
def extract_text_from_first_n_pages(filepath, n):
    text = ""
    with open(filepath, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        for i in range(min(n, len(reader.pages))):
            page = reader.pages[i]
            text += page.extract_text()
    return text
