# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/core/05_analysis.ipynb.

# %% auto 0
__all__ = ['plots_dir']

# %% ../../nbs/core/05_analysis.ipynb 4
import pubcrawler as proj
from .. import const, log, utils, tools
import adu_proj.utils as adutils

# %% ../../nbs/core/05_analysis.ipynb 7
plots_dir = f'{const.pre_output_path}/plots'
os.makedirs(plots_dir, exist_ok=True)
